# configmaps in Kubernetes are used to store non-confidential data in key-value pairs
# configmaps can be used to store configuration settings, environment variables, command-line arguments, and other types of data that can be consumed by pods and containers
# configmaps allow you to decouple configuration data from application code, making it easier to manage and update configuration settings without having to rebuild or redeploy the application
# configmaps can be created using the kubectl command-line tool or by defining them in YAML files
# configmaps can be consumed by pods and containers in several ways, including as environment variables, command-line arguments, or as configuration files mounted as volumes
# configmaps can be updated dynamically, allowing you to change configuration settings without having to restart or redeploy the application
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  limits-memory: "128Mi"
  limits-cpu: "500m"
  requests-memory: "64Mi"
  requests-cpu: "100m"
