apiVersion : v1
kind : Pod
metadata :
  name : Pod with Complete Config
  labels :
    CreatedBy : "Muneer Sir"
    Purpose : "Learning about K8s Complete Pod Config"
    Environment : "Development"
    Team : "DevOps"
spec :
  containers :
    - name : nginx
      image : nginx
      env : 
        - name : "APP_ENV"
          valueFrom :
            configMapKeyRef :
              name: "app-config"
              key: "APP_ENV"
        - name : "APP_VERSION"
          valueFrom :
            configMapKeyRef :
              name : "app-config"
              key : "APP_VERSION"
        
  resources :
        requests :
          memory : "128Mi"
          cpu : "250m"
        limits :
          memory : "256Mi"
          cpu : "500m"
      