apiVersion: v1
kind: Service
metadata:
  name: "Service-dns"
spec:
  type: ClusterIP
  selector:
    app: backend
    project: expense
    environment: development
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 81